# -*- coding: utf-8 -*-
"""
Created on Tue Nov 18 13:18:45 2014

@author: suberlak

Remove first two lines in all DRW lc's generated by Zeljko
"""

import numpy as np

dir_choice=['qso_drw/', 'qso_drw_upd/','qso_drw_long_LC/', 'qso_drw_long_LC_1000/', 'qso_drw_long_LC/conv_time_test/']

dir_input=dir_choice[2]
dir_output=dir_choice[4]



for j in range(1,2):  #4 
    print j
    add  = dir_input+'drw_err'+str(j)+'.list'
    print add 
    names=np.loadtxt(add,dtype=str)
    
    n_LC = 15
    for  i in range(n_LC):   #
          test = np.loadtxt(dir_input+names[i])
          h = np.linspace(300,1500,n_LC).astype(int)
          mjd = test[:,0]
          mag = test[:,1]
          err = test[:,2]
          cols= np.column_stack((mjd[:h[i]],mag[:h[i]],err[:h[i]]))
          print 'Saving LC of length', h[i]
          out =   dir_output + names[i][:10]+str(i)+'_'+str(h[i])+names[i][-8:]    
          np.savetxt(out,cols,fmt="%s")
          print 'Saved ', out
     